Fix assertion message
It previously said `exotic-mod must be loaded. ==> expected: <betamindy> but was: <exotic-mod>` when it failed which makes absolutely no sense.