Fix assertion message (#6448)
It previously said `exotic-mod must be loaded. ==> expected: <betamindy> but was: <exotic-mod>` when it failed which makes absolutely no sense.